name       : exo
version    : 0.11.5
release    : 1
source     :
    - http://archive.xfce.org/src/xfce/exo/0.11/exo-0.11.5.tar.bz2 : 8e8629f33783eba1ce6d092a42c28217458a0cc3d1ad7474097b9187054955c1
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Extension library
description: |
    This is libexo, an extension library to XFCE
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - perl-uri
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
