name       : garcon
version    : 0.6.1
release    : 1
source     :
    - http://archive.xfce.org/src/xfce/garcon/0.6/garcon-0.6.1.tar.bz2 : 41c31ba0498c2cc39de4a8e0c2367510adbf4bc2104c17feee358e51e6acf603
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : freedesktop.org menu specifications
description: |
    Provides an implementation of freedesktop.org menu specification
builddeps  :
    - pkgconfig(libxfce4ui-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
