name       : xfwm4
version    : 4.12.4
release    : 1
source     :
    - http://archive.xfce.org/src/xfce/xfwm4/4.12/xfwm4-4.12.4.tar.bz2 : fa74048a75649a6e92df763a3cfb706d3fed1e1a6adf567f6693325a5a6efb36
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : XFCE window manager
description: |
    XFCE window manager
builddeps  :
    - pkgconfig(xrender)
    - pkgconfig(xcomposite)
    - pkgconfig(libxfce4ui-1)
    - pkgconfig(libwnck-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
